controller.quorum.voters=
1@ip-10-0-3-240.eu-west-1.compute.internal:9093,
2@ip-10-0-3-157.eu-west-1.compute.internal:9093,
3@ip-10-0-3-183.eu-west-1.compute.internal:9093

Node 1
advertised.listeners=SASL_SSL://ip-10-0-3-240.eu-west-1.compute.internal:9092,CONTROLLER://ip-10-0-3-240.eu-west-1.compute.internal:9093,EXTERNAL://54.228.81.173:9094
***
CLUSTER_ID=1710304e-36fb-4165-8adc-913f9739a587

Node 2
advertised.listeners=SASL_SSL://ip-10-0-3-157.eu-west-1.compute.internal:9092,CONTROLLER://ip-10-0-3-157.eu-west-1.compute.internal:9093,EXTERNAL://54.76.47.103:9094
***
CLUSTER_ID=1710304e-36fb-4165-8adc-913f9739a587

Node 3
advertised.listeners=SASL_SSL://ip-10-0-3-183.eu-west-1.compute.internal:9092,CONTROLLER://ip-10-0-3-183.eu-west-1.compute.internal:9093,EXTERNAL://34.244.120.192:9094
***
CLUSTER_ID=1710304e-36fb-4165-8adc-913f9739a587


pache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:444)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:533)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:382)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:302)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:501)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:596)
        at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:110)
        at org.apache.kafka.server.util.InterBrokerSendThread.doWork(InterBrokerSendThread.java:137)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:136)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
        ... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 25 more
[2025-05-26 17:10:44,434] DEBUG Resolved host ip-10-0-3-211.eu-west-1.compute.internal as 10.0.3.211 (org.apache.kafka.clients.ClientUtils)
[2025-05-26 17:10:44,434] DEBUG [RaftManager id=3] Resolved host ip-10-0-3-211.eu-west-1.compute.internal to addresses [ip-10-0-3-211.eu-west-1.compute.internal/10.0.3.211] (org.apache.kafka.clients.ClusterConnectionStates)
[2025-05-26 17:10:44,434] DEBUG [RaftManager id=3] Initiating connection to node ip-10-0-3-211.eu-west-1.compute.internal:9093 (id: 1 rack: null) using address ip-10-0-3-211.eu-west-1.compute.internal/10.0.3.211 (org.apache.kafka.clients.NetworkClient)
[2025-05-26 17:10:44,436] DEBUG [RaftManager id=3] Connection with ip-10-0-3-211.eu-west-1.compute.internal/10.0.3.211 (channelId=1) disconnected (org.apache.kafka.common.network.Selector)
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
        at org.apache.kafka.common.network.SslTransportLayer.finishConnect(SslTransportLayer.java:140)
        at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:224)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:546)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:501)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:596)
        at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:110)
        at org.apache.kafka.server.util.InterBrokerSendThread.doWork(InterBrokerSendThread.java:137)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:136)
[2025-05-26 17:10:44,436] INFO [RaftManager id=3] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2025-05-26 17:10:44,434] ERROR [RaftManager id=3] Unexpected error NETWORK_EXCEPTION in VOTE response: InboundResponse(correlationId=98, data=VoteResponseData(errorCode=13, topics=[], nodeEndpoints=[]), source=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,436] DEBUG [RaftManager id=3] Connection for ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null) is backing off for 18 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,436] WARN [RaftManager id=3] Connection to node 1 (ip-10-0-3-211.eu-west-1.compute.internal/10.0.3.211:9093) could not be established. Node may not be available. (org.apache.kafka.clients.NetworkClient)
[2025-05-26 17:10:44,437] DEBUG [RaftManager id=3] Connection for ip-10-0-3-211.eu-west-1.compute.internal:9093 (id: 1 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,437] DEBUG [RaftManager id=3] Connection for ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null) is backing off for 18 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,455] DEBUG [RaftManager id=3] Connection for ip-10-0-3-211.eu-west-1.compute.internal:9093 (id: 1 rack: null) is backing off for 1 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,457] ERROR [kafka-3-raft-outbound-request-thread]: Failed to send the following request due to authentication error: ClientRequest(expectResponse=true, callback=org.apache.kafka.raft.KafkaNetworkChannel$$Lambda$665/0x000000010051c440@5add8fe6, destination=2, correlationId=100, clientId=raft-client-3, createdTimeMs=1748279444455, requestBuilder=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])])) (org.apache.kafka.raft.KafkaNetworkChannel$SendThread)
[2025-05-26 17:10:44,457] ERROR Request OutboundRequest(correlationId=100, data=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])]), createdTimeMs=1748279444455, destination=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) failed due to authentication error (org.apache.kafka.raft.KafkaNetworkChannel)
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:366)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:304)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
        at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:444)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:533)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:382)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:302)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:501)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:596)
        at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:110)
        at org.apache.kafka.server.util.InterBrokerSendThread.doWork(InterBrokerSendThread.java:137)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:136)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
        ... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 25 more
[2025-05-26 17:10:44,458] ERROR [RaftManager id=3] Unexpected error NETWORK_EXCEPTION in VOTE response: InboundResponse(correlationId=100, data=VoteResponseData(errorCode=13, topics=[], nodeEndpoints=[]), source=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,458] DEBUG [RaftManager id=3] Connection for ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,479] DEBUG [RaftManager id=3] Connection for ip-10-0-3-211.eu-west-1.compute.internal:9093 (id: 1 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,499] ERROR [kafka-3-raft-outbound-request-thread]: Failed to send the following request due to authentication error: ClientRequest(expectResponse=true, callback=org.apache.kafka.raft.KafkaNetworkChannel$$Lambda$665/0x000000010051c440@15162576, destination=2, correlationId=102, clientId=raft-client-3, createdTimeMs=1748279444478, requestBuilder=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])])) (org.apache.kafka.raft.KafkaNetworkChannel$SendThread)
[2025-05-26 17:10:44,500] ERROR Request OutboundRequest(correlationId=102, data=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])]), createdTimeMs=1748279444478, destination=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) failed due to authentication error (org.apache.kafka.raft.KafkaNetworkChannel)
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:366)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:304)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
        at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:444)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:533)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:382)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:302)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:501)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:596)
        at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:110)
        at org.apache.kafka.server.util.InterBrokerSendThread.doWork(InterBrokerSendThread.java:137)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:136)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
        ... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 25 more
[2025-05-26 17:10:44,500] ERROR [RaftManager id=3] Unexpected error NETWORK_EXCEPTION in VOTE response: InboundResponse(correlationId=102, data=VoteResponseData(errorCode=13, topics=[], nodeEndpoints=[]), source=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,501] DEBUG [RaftManager id=3] Connection for ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null) is backing off for 19 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,520] DEBUG [RaftManager id=3] Connection for ip-10-0-3-211.eu-west-1.compute.internal:9093 (id: 1 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,533] INFO [MetadataLoader id=3] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2025-05-26 17:10:44,541] ERROR [kafka-3-raft-outbound-request-thread]: Failed to send the following request due to authentication error: ClientRequest(expectResponse=true, callback=org.apache.kafka.raft.KafkaNetworkChannel$$Lambda$665/0x000000010051c440@4313a863, destination=2, correlationId=104, clientId=raft-client-3, createdTimeMs=1748279444520, requestBuilder=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])])) (org.apache.kafka.raft.KafkaNetworkChannel$SendThread)
[2025-05-26 17:10:44,541] ERROR Request OutboundRequest(correlationId=104, data=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])]), createdTimeMs=1748279444520, destination=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) failed due to authentication error (org.apache.kafka.raft.KafkaNetworkChannel)
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:366)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:304)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
        at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:444)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:533)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:382)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:302)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:501)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:596)
        at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:110)
        at org.apache.kafka.server.util.InterBrokerSendThread.doWork(InterBrokerSendThread.java:137)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:136)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
        ... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 25 more
[2025-05-26 17:10:44,542] ERROR [RaftManager id=3] Unexpected error NETWORK_EXCEPTION in VOTE response: InboundResponse(correlationId=104, data=VoteResponseData(errorCode=13, topics=[], nodeEndpoints=[]), source=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,542] DEBUG [RaftManager id=3] Connection for ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,545] INFO [SocketServer listenerType=BROKER, nodeId=3] Created data-plane acceptor and processors for endpoint : ListenerName(EXTERNAL) (kafka.network.SocketServer)
[2025-05-26 17:10:44,563] DEBUG [RaftManager id=3] Connection for ip-10-0-3-211.eu-west-1.compute.internal:9093 (id: 1 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,584] ERROR [kafka-3-raft-outbound-request-thread]: Failed to send the following request due to authentication error: ClientRequest(expectResponse=true, callback=org.apache.kafka.raft.KafkaNetworkChannel$$Lambda$665/0x000000010051c440@6341fd0a, destination=2, correlationId=106, clientId=raft-client-3, createdTimeMs=1748279444563, requestBuilder=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])])) (org.apache.kafka.raft.KafkaNetworkChannel$SendThread)
[2025-05-26 17:10:44,584] ERROR Request OutboundRequest(correlationId=106, data=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])]), createdTimeMs=1748279444563, destination=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) failed due to authentication error (org.apache.kafka.raft.KafkaNetworkChannel)
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:366)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:304)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
        at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:444)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:533)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:382)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:302)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:501)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:596)
        at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:110)
        at org.apache.kafka.server.util.InterBrokerSendThread.doWork(InterBrokerSendThread.java:137)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:136)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
        ... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 25 more
[2025-05-26 17:10:44,585] ERROR [RaftManager id=3] Unexpected error NETWORK_EXCEPTION in VOTE response: InboundResponse(correlationId=106, data=VoteResponseData(errorCode=13, topics=[], nodeEndpoints=[]), source=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,585] DEBUG [RaftManager id=3] Connection for ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,606] INFO [broker-3-to-controller-alter-partition-channel-manager]: Starting (kafka.server.NodeToControllerRequestThread)
[2025-05-26 17:10:44,610] DEBUG [RaftManager id=3] Connection for ip-10-0-3-211.eu-west-1.compute.internal:9093 (id: 1 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,631] ERROR [kafka-3-raft-outbound-request-thread]: Failed to send the following request due to authentication error: ClientRequest(expectResponse=true, callback=org.apache.kafka.raft.KafkaNetworkChannel$$Lambda$665/0x000000010051c440@5555ec3b, destination=2, correlationId=108, clientId=raft-client-3, createdTimeMs=1748279444605, requestBuilder=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])])) (org.apache.kafka.raft.KafkaNetworkChannel$SendThread)
[2025-05-26 17:10:44,631] ERROR Request OutboundRequest(correlationId=108, data=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])]), createdTimeMs=1748279444605, destination=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) failed due to authentication error (org.apache.kafka.raft.KafkaNetworkChannel)
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:366)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:304)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
        at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:444)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:533)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:382)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:302)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:501)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:596)
        at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:110)
        at org.apache.kafka.server.util.InterBrokerSendThread.doWork(InterBrokerSendThread.java:137)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:136)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
        ... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 25 more
[2025-05-26 17:10:44,632] ERROR [RaftManager id=3] Unexpected error NETWORK_EXCEPTION in VOTE response: InboundResponse(correlationId=108, data=VoteResponseData(errorCode=13, topics=[], nodeEndpoints=[]), source=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,632] DEBUG [RaftManager id=3] Connection for ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,634] INFO [MetadataLoader id=3] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2025-05-26 17:10:44,653] DEBUG [RaftManager id=3] Connection for ip-10-0-3-211.eu-west-1.compute.internal:9093 (id: 1 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,674] ERROR [kafka-3-raft-outbound-request-thread]: Failed to send the following request due to authentication error: ClientRequest(expectResponse=true, callback=org.apache.kafka.raft.KafkaNetworkChannel$$Lambda$665/0x000000010051c440@714c5e72, destination=2, correlationId=110, clientId=raft-client-3, createdTimeMs=1748279444652, requestBuilder=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])])) (org.apache.kafka.raft.KafkaNetworkChannel$SendThread)
[2025-05-26 17:10:44,674] ERROR Request OutboundRequest(correlationId=110, data=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])]), createdTimeMs=1748279444652, destination=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) failed due to authentication error (org.apache.kafka.raft.KafkaNetworkChannel)
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:366)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:304)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
        at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:444)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:533)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:382)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:302)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:501)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:596)
        at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:110)
        at org.apache.kafka.server.util.InterBrokerSendThread.doWork(InterBrokerSendThread.java:137)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:136)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
        ... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 25 more
[2025-05-26 17:10:44,675] ERROR [RaftManager id=3] Unexpected error NETWORK_EXCEPTION in VOTE response: InboundResponse(correlationId=110, data=VoteResponseData(errorCode=13, topics=[], nodeEndpoints=[]), source=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,675] DEBUG [RaftManager id=3] Connection for ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,696] DEBUG [SslTransportLayer channelId=10.0.3.218:9093-10.0.3.189:39078-0 key=channel=java.nio.channels.SocketChannel[connected local=/10.0.3.218:9093 remote=/10.0.3.189:39078], selector=sun.nio.ch.EPollSelectorImpl@3da05cbd, interestOps=1, readyOps=0] SSL Handshake failed (org.apache.kafka.common.network.SslTransportLayer)
javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:192)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:681)
        at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:636)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
        at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:528)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:382)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:302)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:501)
        at kafka.network.Processor.poll(SocketServer.scala:1110)
        at kafka.network.Processor.run(SocketServer.scala:1014)
        at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-26 17:10:44,696] INFO [SocketServer listenerType=CONTROLLER, nodeId=3] Failed authentication with /10.0.3.189 (channelId=10.0.3.218:9093-10.0.3.189:39078-0) (SSL handshake failed) (org.apache.kafka.common.network.Selector)
[2025-05-26 17:10:44,697] DEBUG [RaftManager id=3] Connection for ip-10-0-3-211.eu-west-1.compute.internal:9093 (id: 1 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,717] ERROR [kafka-3-raft-outbound-request-thread]: Failed to send the following request due to authentication error: ClientRequest(expectResponse=true, callback=org.apache.kafka.raft.KafkaNetworkChannel$$Lambda$665/0x000000010051c440@2fc2a088, destination=2, correlationId=112, clientId=raft-client-3, createdTimeMs=1748279444695, requestBuilder=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])])) (org.apache.kafka.raft.KafkaNetworkChannel$SendThread)
[2025-05-26 17:10:44,718] ERROR Request OutboundRequest(correlationId=112, data=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])]), createdTimeMs=1748279444695, destination=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) failed due to authentication error (org.apache.kafka.raft.KafkaNetworkChannel)
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:366)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:304)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1076)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1063)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1010)
        at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:444)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:533)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:382)
        at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:302)
        at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:501)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:596)
        at org.apache.kafka.server.util.InterBrokerSendThread.pollOnce(InterBrokerSendThread.java:110)
        at org.apache.kafka.server.util.InterBrokerSendThread.doWork(InterBrokerSendThread.java:137)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:136)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:632)
        ... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 25 more
[2025-05-26 17:10:44,720] ERROR [RaftManager id=3] Unexpected error NETWORK_EXCEPTION in VOTE response: InboundResponse(correlationId=112, data=VoteResponseData(errorCode=13, topics=[], nodeEndpoints=[]), source=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,720] DEBUG [RaftManager id=3] Connection for ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,734] INFO [MetadataLoader id=3] initializeNewPublishers: the loader is still catching up because we still don't know the high water mark yet. (org.apache.kafka.image.loader.MetadataLoader)
[2025-05-26 17:10:44,741] DEBUG [RaftManager id=3] Connection for ip-10-0-3-211.eu-west-1.compute.internal:9093 (id: 1 rack: null) is backing off for 20 ms (org.apache.kafka.raft.KafkaRaftClient)
[2025-05-26 17:10:44,762] ERROR [kafka-3-raft-outbound-request-thread]: Failed to send the following request due to authentication error: ClientRequest(expectResponse=true, callback=org.apache.kafka.raft.KafkaNetworkChannel$$Lambda$665/0x000000010051c440@4307a1d7, destination=2, correlationId=114, clientId=raft-client-3, createdTimeMs=1748279444740, requestBuilder=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])])) (org.apache.kafka.raft.KafkaNetworkChannel$SendThread)
[2025-05-26 17:10:44,762] ERROR Request OutboundRequest(correlationId=114, data=VoteRequestData(clusterId='1710304e-36fb-4165-8adc-913f9739a587', voterId=2, topics=[TopicData(topicName='__cluster_metadata', partitions=[PartitionData(partitionIndex=0, candidateEpoch=113, candidateId=3, candidateDirectoryId=obc3ed7vKnzEKvWJbaQHxQ, voterDirectoryId=AAAAAAAAAAAAAAAAAAAAAA, lastOffsetEpoch=0, lastOffset=0)])]), createdTimeMs=1748279444740, destination=ip-10-0-3-189.eu-west-1.compute.internal:9093 (id: 2 rack: null)) failed due to authentication error (org.apache.kafka.raft.KafkaNetworkChannel)
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:366)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:304)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at java.base/sun.security.ssl.SSLHandshak